In [18]:
import pandas as pd
import numpy as np

In [81]:
np.random.seed(0)
m1=np.random.randint(1,10,(5,3))

In [82]:
m1

array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5],
       [8, 7, 9],
       [9, 2, 7]])

In [83]:
exp=pd.DataFrame(m1,["Mon","Tue","Wed","Thu","Fri"],["Almond","Peanut","Cashew"])
exp

Almond  Peanut  Cashew
Mon       6       1       4
Tue       4       8       4
Wed       6       3       5
Thu       8       7       9
Fri       9       2       7

In [84]:
m2=np.array([2,5,8])
m2

array([2, 5, 8])

In [85]:
m2.reshape(1,3)

array([[2, 5, 8]])

In [86]:
exp2=pd.DataFrame(m2.reshape(1,3),["Price"],["Almond","Peanut","Cashew"])

In [87]:
exp2

Almond  Peanut  Cashew
Price       2       5       8

In [88]:
m3=np.dot(m1,m2)
m3

array([ 49,  80,  67, 123,  84])

In [89]:
m1.shape

(5, 3)

In [90]:
m2.shape

(3,)

In [91]:
m3=m1.dot(m2.T)

In [92]:
exp

Almond  Peanut  Cashew
Mon       6       1       4
Tue       4       8       4
Wed       6       3       5
Thu       8       7       9
Fri       9       2       7

In [95]:
m3

array([ 49,  80,  67, 123,  84])

In [96]:
exp["Total sales"]=m3

In [97]:
exp

Almond  Peanut  Cashew  Total sales
Mon       6       1       4           49
Tue       4       8       4           80
Wed       6       3       5           67
Thu       8       7       9          123
Fri       9       2       7           84

In [98]:
exp2

Almond  Peanut  Cashew
Price       2       5       8