# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.dtype,a1.size,type(a1)

((3,), dtype('int64'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape,a2.dtype,a2.size,type(a2)

((3, 3), dtype('int64'), 9, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape,a3.size,a3.dtype,type(a3)

((3, 3, 3), 27, dtype('int64'), numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df1=pd.DataFrame(a2)
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[8, 4],
       [8, 2],
       [4, 1],
       [5, 1],
       [9, 4],
       [5, 7],
       [8, 6]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random((3,5))

array([[0.60120878, 0.27375399, 0.53569325, 0.53111143, 0.23472708],
       [0.93325542, 0.82179224, 0.90969131, 0.28766549, 0.74453148],
       [0.56981515, 0.4534356 , 0.79850318, 0.45716586, 0.49315512]])

In [22]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [25]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
var1=np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(var1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# Find the 0'th index of the latest array you created
var1[0]

array([7, 8, 3, 1, 4, 2, 8])

In [29]:
# Get the first 2 rows of latest array you created
print(var1[0:3])

[[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]]


In [31]:
# Get the first 2 values of the first 2 rows of the latest array
var1[0:2,0:2]

array([[7, 8],
       [4, 2]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ran1=np.random.randint(0,10,(3,5))
ran2=np.ones((3,5))

In [35]:
# Add the two arrays together
ran1+ran2

array([[ 1.,  8.,  3.,  3.,  1.],
       [ 5., 10.,  7., 10.,  9.],
       [ 7.,  9.,  8.,  2.,  1.]])

In [36]:
# Create another array of ones of shape (5, 3)
ran3=np.ones((5,3))

In [37]:
# Try add the array of ones and the other most recent array together
ran3+ran2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [38]:
# Create another array of ones of shape (3, 5)
ran3=np.ones((3,5))

In [39]:
# Subtract the new array of ones from the other most recent array
ran2-ran3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
# Multiply the ones array with the latest array
ran3*ran1

array([[0., 7., 2., 2., 0.],
       [4., 9., 6., 9., 8.],
       [6., 8., 7., 1., 0.]])

In [41]:
# Take the latest array to the power of 2 using '**'
ran1**2

array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [42]:
# Do the same thing with np.square()
np.square(ran1)

array([[ 0, 49,  4,  4,  0],
       [16, 81, 36, 81, 64],
       [36, 64, 49,  1,  0]])

In [44]:
# Find the mean of the latest array using np.mean()
np.mean(ran1)

4.6

In [45]:
# Find the maximum of the latest array using np.max()
np.max(ran1)

9

In [46]:
# Find the minimum of the latest array using np.min()
np.min(ran1)

0

In [47]:
# Find the standard deviation of the latest array
np.std(ran1)

3.3426536364591137

In [48]:
# Find the variance of the latest array
np.var(ran1)

11.173333333333336

In [50]:
# Reshape the latest array to (3, 5, 1)
ran1=np.reshape(ran1,(3,5,1))

In [52]:
# Transpose the latest array
ran1.T

array([[[0, 4, 6],
        [7, 9, 8],
        [2, 6, 7],
        [2, 9, 1],
        [0, 8, 0]]])

What does the transpose do?

In [53]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ran1=np.random.randint(0,10,(3,3))
ran2=np.random.randint(0,10,(3,2))

In [54]:
# Perform a dot product on the two newest arrays you created
ran1.dot(ran2)

array([[52, 87],
       [40, 79],
       [14, 20]])

In [55]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ran1=np.random.randint(0,10,(4,3))
ran2=np.random.randint(0,10,(4,3))

In [56]:
# Perform a dot product on the two newest arrays you created
np.dot(ran1,ran2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ran1.T.dot(ran2)

array([[123, 120,  96],
       [ 74,  75,  81],
       [109,  76, 116]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ran1=np.random.randint(0,10,(3,3))
ran2=np.random.randint(0,10,(3,3))

In [59]:
# Compare the two arrays with '>'
ran1>ran2

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True, False]])

What happens when you compare the arrays with `>`?

In [60]:
# Compare the two arrays with '>='
ran1>=ran2

array([[ True,  True,  True],
       [False, False,  True],
       [ True,  True, False]])

In [61]:
# Find which elements of the first array are greater than 7
ran1>7

array([[False,  True, False],
       [False, False,  True],
       [ True, False,  True]])

In [64]:
# Which parts of each array are equal? (try using '==')
ran1==ran2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [65]:
# Sort one of the arrays you just created in ascending order
ran1.sort()

In [67]:
# Sort the indexes of one of the arrays you just created
ran1.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [69]:
# Find the index with the maximum value in one of the arrays you've created
ran1.argmax()

2

In [70]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ran1)

3

In [71]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
ran1.argmax(axis=1)

array([2, 2, 1])

In [72]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
ran1.argmin(axis=0)

array([1, 1, 0])

In [73]:
# Create an array of normally distributed random numbers
np.random.randn()

0.45293632653350946

In [74]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.